kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 0Qq0q0lfKOWjdgUf7GcoRLBeWkCr1VZjdw+i7wnmFrI=
      - identity: {}
