---
- name: Configure NGINX on Master Nodes
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install nginx
      apt: name=nginx state=latest
    - name: configure nginx
      ansible.builtin.shell: |
        cat > kubernetes.default.svc.cluster.local <<EOF
        server {
          listen      80;
          server_name kubernetes.default.svc.cluster.local;

          location /healthz {
             proxy_pass                    https://127.0.0.1:6443/healthz;
             proxy_ssl_trusted_certificate /var/lib/kubernetes/ca.pem;
          }
        }
        EOF
        
        mv kubernetes.default.svc.cluster.local \
          /etc/nginx/sites-available/kubernetes.default.svc.cluster.local

        ln -s /etc/nginx/sites-available/kubernetes.default.svc.cluster.local /etc/nginx/sites-enabled/
    - name: Restart nginx
      ansible.builtin.systemd:
        state: restarted
        name: nginx
    - name: Enable nginx
      ansible.builtin.systemd:
        enabled: true
        name: nginx
